### ISSUE TITLE
Locahost:3000 won't find ejs templates.

### ISSUE THREAD

**Issue by jcdavison** [flovilmart/parse-develop#16]
Hey there, cool lib, I'm kind surprised how parse doesn't have a native web server in local development mode.  

I'm tinkering with their tutorial, https://github.com/ParsePlatform/Anyimg

And I'm getting an error message in local development anytime I attempt to render an ejs template.  

![http://cl.ly/image/2V1A2P440u0Q/Image%202015-03-11%20at%202.50.17%20PM.png](http://cl.ly/image/2V1A2P440u0Q/Image%202015-03-11%20at%202.50.17%20PM.png)

I'm note particularly experienced to node though I have lots of ruby/rails and some node experience.  I'm 'sure' these templates work in production, you can look at the app I'm tinkering with, https://any-image-example.parseapp.com/signup

Thoughts on what direction to take this? I'm kind of curious if you have any thoughts on using parse for serious web hosting as well.  Cheers, JD

**Comment by flovilmart** [comment]
It looks like parse's express module in production uses a singleton when calling express, where my express fork creates a new instance every times. I'll look into it an push to the according module

**Comment by jcdavison** [comment]
:smile:

**Comment by flovilmart** [comment]
So I found out why it doesn't loads the views:
in my express's fork in application.js, each time a new express() is called, all the settings are reinitialized. to the default, it looks like in parse, the settings are inherited from the parent/ copied at the time app.use is called

**Comment by flovilmart** [comment]
The quick hack for you to solve that and get going would be to add at line 63 of application.js (the applicaiton.js referenced in the crashlog)   this.settings = parent.settings; so the on('mount') look like that: 

  this.on('mount', function(parent){
    this.request.__proto__ = parent.request;
    this.response.__proto__ = parent.response;
    this.engines.__proto__ = parent.engines;
    this.settings = parent.settings;
  });

**Comment by flovilmart** [comment]
I've updated flovilmart/express#3.1.0-parse so the views configuration is not reset each time a new app is created
