### ISSUE TITLE
Trouble getting cloud code to run locally

### ISSUE THREAD

**Issue by dfinzer** [flovilmart/parse-develop#17]
Hey there, awesome library. My app is set up, but I'm having trouble getting Parse Cloud Functions to run locally. For example, I added a helloWorld Cloud function to my main.js. When I call this from Javascript from my webapp, however, it still seems to be calling the Parse production API.

![image](https://cloud.githubusercontent.com/assets/613881/6633044/ee1884bc-c8fe-11e4-8a39-12ef4c1f86b3.png)

I've added my javascriptKey to the global config; is there anything else I have to do?

**Comment by flovilmart** [comment]
The cloud functions are not called from the local server as described in the README

**Comment by dfinzer** [comment]
Ah I see, sorry I misread the readme. Thank you!
