### ISSUE TITLE
Forever detected script exited with code 0

### ISSUE THREAD

**Issue by igorbarinov** [flovilmart/parse-develop#18]
How to debug?

**Comment by flovilmart** [comment]
Have you properly followed the directives in the README file?

**Comment by igorbarinov** [comment]
for testing purposes I created a clean VM on terminal.com with Ubuntu and Node

installed 
npm install parse-develop -g
created new app using
parse new MyApp
added 
javascriptKey
and started it

**Comment by igorbarinov** [comment]
Same result :disappointed: 
Watching /root/test/Block
Starting app Block Notary
[14789] Running on http://localhost:3000/
Forever detected script exited with code 0

**Comment by flovilmart** [comment]
Have you tried to update the parsedev rc configuration with debug:true?

**Comment by flovilmart** [comment]
And with parse new, there's no express app being created by default as I can recall, so forever doesn't have anything to run

**Comment by igorbarinov** [comment]
i've created ~/.parsedevrc with "debug=1" inside
is it correct way to use rc?

**Comment by flovilmart** [comment]
There's the full documentation of rc linked in the readme file

**Comment by igorbarinov** [comment]
Sorry for my noobish questions. I am new for some of technologies.
Yeah I've read README several times :)
"It is possible to change the behavior of forever monitor through a rc file (we use the rc module)."
but no point where I should put it. For me its second time I use rc file. First was with bashrc. 
I stated to look into rc module documentation https://www.npmjs.com/package/rc

>command line arguments (parsed by minimist)
>environment variables prefixed with ${appname}_
>or use "__" to indicate nested properties 
>(e.g. appname_foo__bar__baz => foo.bar.baz)
>if you passed an option --config file then from that file
>a local .${appname}rc or the first found looking in ./ ../ ../../ ../../../ etc.
>$HOME/.${appname}rc
>$HOME/.${appname}/config
>$HOME/.config/${appname}
>$HOME/.config/${appname}/config
>/etc/${appname}rc
>/etc/${appname}/config
>the defaults object you passed in.

am I right?

**Comment by flovilmart** [comment]
Have you first made sure you have an express app defined in your new parse app?




As explained here:




https://www.parse.com/docs/js/guide#hosting





And the section Dynamic Websites 




This project is only intending to facilitate the development of express websites locally, without pushing the changes to parse at each change.

**Comment by flovilmart** [comment]
@igorbarinov 

So in order to use this project:

1. Create a new parse app (if needed)

    `$ parse new MyApp`

2. Get in to the app foler
    `$ cd MyApp`

3. Edit the config/global.json 
4. Generate a skeleton express app:
    `$ parse generate express` 

5. Update main.js with the following at the top

    `require("cloud/app.js")`
    
6. Run parse-develop

    `$ parse-develop`

7. Visit http://localhost:8080


Does that help?
